import type { NormalizedCompany } from "@/lib/ingestion/types";
import {
  computeStrategicRelevanceScore,
  STRATEGIC_SEED_SOURCE,
  type StrategicSeedMeta,
} from "@/lib/scoring/strategic-relevance";

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
}

function strategicSeed(
  partial: Omit<
    NormalizedCompany,
    "sources" | "discoverySources" | "sourceKind" | "strategicRelevanceScore"
  > &
    StrategicSeedMeta & {
      sources?: NormalizedCompany["sources"];
    }
): NormalizedCompany {
  const fetchedAt = new Date().toISOString();
  const { strategicTier, europePmRelevance, ...companyFields } = partial;

  return {
    ...companyFields,
    discoverySources: [STRATEGIC_SEED_SOURCE],
    sourceKind: "seed",
    strategicRelevanceScore: computeStrategicRelevanceScore({
      strategicTier,
      europePmRelevance,
    }),
    sources: partial.sources ?? {
      name: { value: partial.name, source: STRATEGIC_SEED_SOURCE, fetchedAt },
    },
  };
}

/** Globally important AI/product companies relevant to Paris/Europe senior PM opportunities. */
export const STRATEGIC_SEED_COMPANIES: NormalizedCompany[] = [
  strategicSeed({
    name: "Sierra",
    website: "https://sierra.ai",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 175_000_000,
    fundingRound: "Series C",
    fundingDate: daysAgo(40),
    aiCategory: "Enterprise AI",
    businessModel: "Enterprise SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 28,
    pmRoles: 3,
    aiRoles: 10,
    engRoles: 15,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Enterprise AI agents for customer experience. Strategic target for senior PM roles in Europe and remote-EU expansion.",
  }),
  strategicSeed({
    name: "Databricks",
    website: "https://databricks.com",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Series I",
    fundingDate: daysAgo(120),
    aiCategory: "Data Platform",
    businessModel: "Enterprise SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 120,
    pmRoles: 12,
    aiRoles: 40,
    engRoles: 68,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Unified data and AI platform with strong European enterprise presence. Relevant for senior PM roles in Paris and remote-EU.",
  }),
  strategicSeed({
    name: "Snowflake",
    website: "https://snowflake.com",
    hqCity: "Bozeman",
    hqCountry: "United States",
    fundingAmountUsd: 1_500_000_000,
    fundingRound: "Growth",
    fundingDate: daysAgo(200),
    aiCategory: "Data Platform",
    businessModel: "Enterprise SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 80,
    pmRoles: 8,
    aiRoles: 25,
    engRoles: 47,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Cloud data platform expanding AI workloads. Large European go-to-market with PM hiring in major EU hubs.",
  }),
  strategicSeed({
    name: "Perplexity",
    website: "https://perplexity.ai",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Series D",
    fundingDate: daysAgo(30),
    aiCategory: "AI Product",
    businessModel: "B2C",
    industry: "Artificial Intelligence",
    openRolesTotal: 45,
    pmRoles: 4,
    aiRoles: 18,
    engRoles: 23,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "medium",
    description:
      "AI-native search and answer engine. Strategic target for product leadership as European user base scales.",
  }),
  strategicSeed({
    name: "Harvey",
    website: "https://harvey.ai",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 300_000_000,
    fundingRound: "Series D",
    fundingDate: daysAgo(45),
    aiCategory: "Enterprise AI",
    businessModel: "Enterprise SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 35,
    pmRoles: 3,
    aiRoles: 12,
    engRoles: 20,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "AI assistant for legal professionals with growing European law firm adoption. Strategic PM target for EU expansion.",
  }),
  strategicSeed({
    name: "Glean",
    website: "https://glean.com",
    hqCity: "Palo Alto",
    hqCountry: "United States",
    fundingAmountUsd: 260_000_000,
    fundingRound: "Series E",
    fundingDate: daysAgo(55),
    aiCategory: "Enterprise AI",
    businessModel: "Enterprise SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 40,
    pmRoles: 4,
    aiRoles: 14,
    engRoles: 22,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Work AI platform for enterprise knowledge search. Strong EMEA enterprise sales motion relevant to Paris PM roles.",
  }),
  strategicSeed({
    name: "Writer",
    website: "https://writer.com",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 200_000_000,
    fundingRound: "Series C",
    fundingDate: daysAgo(70),
    aiCategory: "Enterprise AI",
    businessModel: "Enterprise SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 30,
    pmRoles: 3,
    aiRoles: 10,
    engRoles: 17,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "medium",
    description:
      "Enterprise generative AI writing platform. Strategic target for senior PM opportunities in European enterprise accounts.",
  }),
  strategicSeed({
    name: "Cognition",
    website: "https://cognition.ai",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 400_000_000,
    fundingRound: "Series C",
    fundingDate: daysAgo(25),
    aiCategory: "Developer Tools",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 25,
    pmRoles: 2,
    aiRoles: 12,
    engRoles: 11,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "medium",
    description:
      "Creators of Devin, the AI software engineer. Strategic target for senior PM roles in developer AI products.",
  }),
  strategicSeed({
    name: "Cursor",
    website: "https://cursor.com",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Series C",
    fundingDate: daysAgo(20),
    aiCategory: "Developer Tools",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 40,
    pmRoles: 4,
    aiRoles: 15,
    engRoles: 21,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Anysphere's AI-native code editor used globally by engineers. High-priority strategic target for senior PM roles in Europe.",
  }),
  strategicSeed({
    name: "Lovable",
    website: "https://lovable.dev",
    hqCity: "Stockholm",
    hqCountry: "Sweden",
    fundingAmountUsd: 200_000_000,
    fundingRound: "Series A",
    fundingDate: daysAgo(35),
    aiCategory: "Developer Tools",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 20,
    pmRoles: 2,
    aiRoles: 8,
    engRoles: 10,
    workMode: "Remote",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "AI app builder from Sweden with strong European product culture. Strategic target for senior PM roles in Paris and remote-EU.",
  }),
  strategicSeed({
    name: "Vercel",
    website: "https://vercel.com",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 250_000_000,
    fundingRound: "Series E",
    fundingDate: daysAgo(90),
    aiCategory: "Developer Tools",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 35,
    pmRoles: 4,
    aiRoles: 10,
    engRoles: 21,
    workMode: "Remote",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Frontend cloud and AI SDK platform with global developer adoption. Relevant for senior PM roles in Europe and remote-EU.",
  }),
  strategicSeed({
    name: "Linear",
    website: "https://linear.app",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 82_000_000,
    fundingRound: "Series C",
    fundingDate: daysAgo(60),
    aiCategory: "Developer Tools",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 18,
    pmRoles: 2,
    aiRoles: 5,
    engRoles: 11,
    workMode: "Remote",
    strategicTier: 2,
    europePmRelevance: "high",
    description:
      "Modern product development tool with remote-first culture. Strategic target for senior PM roles across Europe.",
  }),
  strategicSeed({
    name: "Ramp",
    website: "https://ramp.com",
    hqCity: "New York",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Series D+",
    fundingDate: daysAgo(50),
    aiCategory: "Enterprise AI",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 45,
    pmRoles: 5,
    aiRoles: 12,
    engRoles: 28,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "medium",
    description:
      "AI-powered finance operations platform scaling rapidly. Strategic PM target as fintech AI expands internationally.",
  }),
  strategicSeed({
    name: "Brex",
    website: "https://brex.com",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Series D+",
    fundingDate: daysAgo(100),
    aiCategory: "Enterprise AI",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 40,
    pmRoles: 4,
    aiRoles: 10,
    engRoles: 26,
    workMode: "Hybrid",
    strategicTier: 2,
    europePmRelevance: "medium",
    description:
      "Corporate card and spend management with AI automation. Strategic target for senior PM roles in fintech AI.",
  }),
  strategicSeed({
    name: "Clay",
    website: "https://clay.com",
    hqCity: "New York",
    hqCountry: "United States",
    fundingAmountUsd: 100_000_000,
    fundingRound: "Series C",
    fundingDate: daysAgo(40),
    aiCategory: "Enterprise AI",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 22,
    pmRoles: 2,
    aiRoles: 7,
    engRoles: 13,
    workMode: "Hybrid",
    strategicTier: 2,
    europePmRelevance: "medium",
    description:
      "AI-powered GTM and data enrichment platform. Strategic target for senior PM roles in sales AI products.",
  }),
  strategicSeed({
    name: "Intercom",
    website: "https://intercom.com",
    hqCity: "Dublin",
    hqCountry: "Ireland",
    fundingAmountUsd: 125_000_000,
    fundingRound: "Series D+",
    fundingDate: daysAgo(60),
    aiCategory: "Enterprise AI",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 35,
    pmRoles: 4,
    aiRoles: 12,
    engRoles: 19,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "AI-first customer service platform headquartered in Dublin. Strong European PM hiring signal for Paris-adjacent roles.",
  }),
  strategicSeed({
    name: "Synthesia",
    website: "https://synthesia.io",
    hqCity: "London",
    hqCountry: "United Kingdom",
    fundingAmountUsd: 90_000_000,
    fundingRound: "Series C",
    fundingDate: daysAgo(55),
    aiCategory: "Consumer AI",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 28,
    pmRoles: 3,
    aiRoles: 9,
    engRoles: 16,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "AI video generation for enterprise with London HQ. Strategic target for senior PM roles in European generative AI.",
  }),
  strategicSeed({
    name: "Runway",
    website: "https://runwayml.com",
    hqCity: "New York",
    hqCountry: "United States",
    fundingAmountUsd: 308_000_000,
    fundingRound: "Series D",
    fundingDate: daysAgo(45),
    aiCategory: "AI Product",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 30,
    pmRoles: 3,
    aiRoles: 12,
    engRoles: 15,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "medium",
    description:
      "Generative AI video platform for creators and enterprises. Strategic PM target for European creative AI markets.",
  }),
  strategicSeed({
    name: "Scale AI",
    website: "https://scale.com",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Series F",
    fundingDate: daysAgo(80),
    aiCategory: "AI Infrastructure",
    businessModel: "Enterprise SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 50,
    pmRoles: 4,
    aiRoles: 20,
    engRoles: 26,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "medium",
    description:
      "Data infrastructure for AI model training and evaluation. Strategic target for senior PM roles in AI infrastructure.",
  }),
  strategicSeed({
    name: "OpenAI",
    website: "https://openai.com",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Series E",
    fundingDate: daysAgo(60),
    aiCategory: "LLM Platform",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 200,
    pmRoles: 15,
    aiRoles: 80,
    engRoles: 105,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Frontier AI lab with ChatGPT and enterprise API. Strategic target for senior PM roles in European AI product expansion.",
  }),
  strategicSeed({
    name: "Anthropic",
    website: "https://anthropic.com",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Series E",
    fundingDate: daysAgo(55),
    aiCategory: "LLM Platform",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 120,
    pmRoles: 10,
    aiRoles: 50,
    engRoles: 60,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Claude AI provider with growing European enterprise adoption. Strategic target for senior PM roles in EU market expansion.",
  }),
  strategicSeed({
    name: "Stripe",
    website: "https://stripe.com",
    hqCity: "San Francisco",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Series I",
    fundingDate: daysAgo(150),
    aiCategory: "Enterprise AI",
    businessModel: "B2B SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 100,
    pmRoles: 10,
    aiRoles: 25,
    engRoles: 65,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Payments infrastructure with Dublin engineering hub and AI-powered products. Strong European PM hiring signal.",
  }),
  strategicSeed({
    name: "Datadog",
    website: "https://datadoghq.com",
    hqCity: "New York",
    hqCountry: "United States",
    fundingAmountUsd: 500_000_000,
    fundingRound: "Growth",
    fundingDate: daysAgo(180),
    aiCategory: "Data Platform",
    businessModel: "Enterprise SaaS",
    industry: "Artificial Intelligence",
    openRolesTotal: 70,
    pmRoles: 6,
    aiRoles: 20,
    engRoles: 44,
    workMode: "Hybrid",
    strategicTier: 1,
    europePmRelevance: "high",
    description:
      "Observability and security platform with Paris office and AI observability products. Strategic PM target for France/EU.",
  }),
];
