import type { NormalizedCompany } from "../src/lib/ingestion/types";

function daysAgo(n: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d;
}

function seed(
  partial: Omit<NormalizedCompany, "sources"> & { sources?: NormalizedCompany["sources"] }
): NormalizedCompany {
  const fetchedAt = new Date().toISOString();
  return {
    ...partial,
    sources: partial.sources ?? {
      name: { value: partial.name, source: "seed", fetchedAt },
    },
  };
}

export const SEED_COMPANIES: NormalizedCompany[] = [
  seed({ name: "Mistral AI", website: "https://mistral.ai", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 600_000_000, fundingRound: "Series B", fundingDate: daysAgo(45), aiCategory: "LLM Platform", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 35, pmRoles: 4, aiRoles: 15, engRoles: 16, workMode: "Hybrid", description: "European frontier AI lab building open-weight LLMs." }),
  seed({ name: "Poolside", website: "https://poolside.ai", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 500_000_000, fundingRound: "Series B", fundingDate: daysAgo(60), aiCategory: "Developer Tools", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 28, pmRoles: 3, aiRoles: 12, engRoles: 13, workMode: "Remote", description: "AI-powered software development platform." }),
  seed({ name: "H Company", website: "https://hcompany.ai", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 220_000_000, fundingRound: "Series B", fundingDate: daysAgo(90), aiCategory: "Agentic AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 22, pmRoles: 2, aiRoles: 10, engRoles: 10, workMode: "Hybrid", description: "Building autonomous AI agents for enterprise workflows." }),
  seed({ name: "Photoroom", website: "https://photoroom.com", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 43_000_000, fundingRound: "Series B", fundingDate: daysAgo(30), aiCategory: "Consumer AI", businessModel: "B2C", industry: "Artificial Intelligence", openRolesTotal: 18, pmRoles: 2, aiRoles: 6, engRoles: 10, workMode: "Hybrid", description: "AI photo editing app for e-commerce and creators." }),
  seed({ name: "Dust", website: "https://dust.tt", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 16_000_000, fundingRound: "Series A", fundingDate: daysAgo(75), aiCategory: "Agentic AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 12, pmRoles: 1, aiRoles: 5, engRoles: 6, workMode: "Hybrid", description: "Custom AI agents for team knowledge work." }),
  seed({ name: "Gladia", website: "https://gladia.io", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 16_000_000, fundingRound: "Series A", fundingDate: daysAgo(55), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 10, pmRoles: 1, aiRoles: 4, engRoles: 5, workMode: "Remote", description: "Speech-to-text API powered by AI." }),
  seed({ name: "Aqemia", website: "https://aqemia.com", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 38_000_000, fundingRound: "Series A", fundingDate: daysAgo(40), aiCategory: "Healthcare AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 15, pmRoles: 2, aiRoles: 6, engRoles: 7, workMode: "Hybrid", description: "AI-driven drug discovery platform." }),
  seed({ name: "Owkin", website: "https://owkin.com", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 80_000_000, fundingRound: "Series B", fundingDate: daysAgo(100), aiCategory: "Healthcare AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 20, pmRoles: 2, aiRoles: 8, engRoles: 10, workMode: "Hybrid", description: "Federated learning for medical research." }),
  seed({ name: "Alan", website: "https://alan.com", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 193_000_000, fundingRound: "Series F", fundingDate: daysAgo(120), aiCategory: "Healthcare AI", businessModel: "B2B2C", industry: "Artificial Intelligence", openRolesTotal: 30, pmRoles: 4, aiRoles: 8, engRoles: 18, workMode: "Hybrid", description: "AI-powered health insurance platform." }),
  seed({ name: "Shift Technology", website: "https://shift-technology.com", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 220_000_000, fundingRound: "Series D+", fundingDate: daysAgo(80), aiCategory: "Enterprise AI", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 25, pmRoles: 3, aiRoles: 7, engRoles: 15, workMode: "Hybrid", description: "AI for insurance claims automation." }),

  seed({ name: "Aleph Alpha", website: "https://aleph-alpha.com", hqCity: "Heidelberg", hqCountry: "Germany", fundingAmountUsd: 500_000_000, fundingRound: "Series B", fundingDate: daysAgo(50), aiCategory: "LLM Platform", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 30, pmRoles: 3, aiRoles: 14, engRoles: 13, workMode: "Hybrid", description: "European sovereign AI with Luminous models." }),
  seed({ name: "DeepL", website: "https://deepl.com", hqCity: "Cologne", hqCountry: "Germany", fundingAmountUsd: 300_000_000, fundingRound: "Series C", fundingDate: daysAgo(70), aiCategory: "NLP", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 40, pmRoles: 5, aiRoles: 12, engRoles: 23, workMode: "Hybrid", description: "AI translation and writing platform." }),
  seed({ name: "Celonis", website: "https://celonis.com", hqCity: "Munich", hqCountry: "Germany", fundingAmountUsd: 1_000_000_000, fundingRound: "Series D+", fundingDate: daysAgo(150), aiCategory: "Enterprise AI", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 50, pmRoles: 6, aiRoles: 15, engRoles: 29, workMode: "Hybrid", description: "Process mining with AI-powered insights." }),
  seed({ name: "Black Forest Labs", website: "https://blackforestlabs.ai", hqCity: "Freiburg", hqCountry: "Germany", fundingAmountUsd: 31_000_000, fundingRound: "Seed", fundingDate: daysAgo(35), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 8, pmRoles: 0, aiRoles: 5, engRoles: 3, workMode: "Remote", description: "Creators of FLUX open-source image models." }),
  seed({ name: "Parloa", website: "https://parloa.com", hqCity: "Berlin", hqCountry: "Germany", fundingAmountUsd: 66_000_000, fundingRound: "Series B", fundingDate: daysAgo(65), aiCategory: "Enterprise AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 20, pmRoles: 2, aiRoles: 7, engRoles: 11, workMode: "Hybrid", description: "AI agent platform for customer service." }),
  seed({ name: "N8n", website: "https://n8n.io", hqCity: "Berlin", hqCountry: "Germany", fundingAmountUsd: 60_000_000, fundingRound: "Series B", fundingDate: daysAgo(85), aiCategory: "Developer Tools", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 22, pmRoles: 2, aiRoles: 5, engRoles: 15, workMode: "Remote", description: "Workflow automation with AI integrations." }),
  seed({ name: "Langfuse", website: "https://langfuse.com", hqCity: "Berlin", hqCountry: "Germany", fundingAmountUsd: 4_000_000, fundingRound: "Seed", fundingDate: daysAgo(25), aiCategory: "Developer Tools", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 6, pmRoles: 1, aiRoles: 2, engRoles: 3, workMode: "Remote", description: "Open-source LLM engineering platform." }),
  seed({ name: "Merantix", website: "https://merantix.com", hqCity: "Berlin", hqCountry: "Germany", fundingAmountUsd: 50_000_000, fundingRound: "Series A", fundingDate: daysAgo(95), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 15, pmRoles: 1, aiRoles: 8, engRoles: 6, workMode: "Hybrid", description: "AI venture studio building ML companies." }),

  seed({ name: "Synthesia", website: "https://synthesia.io", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 90_000_000, fundingRound: "Series C", fundingDate: daysAgo(55), aiCategory: "Consumer AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 25, pmRoles: 3, aiRoles: 8, engRoles: 14, workMode: "Hybrid", description: "AI video generation for enterprise." }),
  seed({ name: "Stability AI", website: "https://stability.ai", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 80_000_000, fundingRound: "Series A", fundingDate: daysAgo(110), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 20, pmRoles: 2, aiRoles: 10, engRoles: 8, workMode: "Remote", description: "Open-source generative AI models." }),
  seed({ name: "Wayve", website: "https://wayve.ai", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 1_000_000_000, fundingRound: "Series C", fundingDate: daysAgo(40), aiCategory: "Computer Vision", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 35, pmRoles: 3, aiRoles: 15, engRoles: 17, workMode: "Hybrid", description: "Embodied AI for autonomous driving." }),
  seed({ name: "PolyAI", website: "https://poly.ai", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 50_000_000, fundingRound: "Series C", fundingDate: daysAgo(60), aiCategory: "Enterprise AI", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 18, pmRoles: 2, aiRoles: 6, engRoles: 10, workMode: "Hybrid", description: "Conversational AI for customer service." }),
  seed({ name: "Faculty", website: "https://faculty.ai", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 42_000_000, fundingRound: "Series A", fundingDate: daysAgo(130), aiCategory: "Enterprise AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 15, pmRoles: 2, aiRoles: 5, engRoles: 8, workMode: "Hybrid", description: "Applied AI for enterprise decision-making." }),
  seed({ name: "Graphcore", website: "https://graphcore.ai", hqCity: "Bristol", hqCountry: "United Kingdom", fundingAmountUsd: 222_000_000, fundingRound: "Series E", fundingDate: daysAgo(160), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 12, pmRoles: 1, aiRoles: 4, engRoles: 7, workMode: "Hybrid", description: "Intelligence Processing Units for AI." }),
  seed({ name: "BenevolentAI", website: "https://benevolent.com", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 90_000_000, fundingRound: "Series D+", fundingDate: daysAgo(140), aiCategory: "Healthcare AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 16, pmRoles: 2, aiRoles: 7, engRoles: 7, workMode: "Hybrid", description: "AI drug discovery and development." }),

  seed({ name: "ElevenLabs", website: "https://elevenlabs.io", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 180_000_000, fundingRound: "Series C", fundingDate: daysAgo(20), aiCategory: "AI Product", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 30, pmRoles: 3, aiRoles: 10, engRoles: 17, workMode: "Remote", description: "AI voice synthesis and cloning platform." }),
  seed({ name: "Harvey", website: "https://harvey.ai", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 100_000_000, fundingRound: "Series C", fundingDate: daysAgo(45), aiCategory: "Enterprise AI", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 22, pmRoles: 2, aiRoles: 8, engRoles: 12, workMode: "Hybrid", description: "AI assistant for legal professionals." }),

  seed({ name: "Typeface", website: "https://typeface.ai", hqCity: "Amsterdam", hqCountry: "Netherlands", fundingAmountUsd: 100_000_000, fundingRound: "Series B", fundingDate: daysAgo(80), aiCategory: "Enterprise AI", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 20, pmRoles: 2, aiRoles: 7, engRoles: 11, workMode: "Hybrid", description: "Generative AI for enterprise marketing." }),
  seed({ name: "Adyton", website: "https://adyton.ai", hqCity: "Amsterdam", hqCountry: "Netherlands", fundingAmountUsd: 5_000_000, fundingRound: "Seed", fundingDate: daysAgo(15), aiCategory: "Agentic AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 5, pmRoles: 1, aiRoles: 2, engRoles: 2, workMode: "Remote", description: "AI agents for supply chain optimization." }),

  seed({ name: "Neural Concept", website: "https://neuralconcept.com", hqCity: "Lausanne", hqCountry: "Switzerland", fundingAmountUsd: 27_000_000, fundingRound: "Series A", fundingDate: daysAgo(70), aiCategory: "Enterprise AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 10, pmRoles: 1, aiRoles: 4, engRoles: 5, workMode: "Hybrid", description: "Deep learning for engineering simulation." }),
  seed({ name: "Swiss AI", website: "https://swiss-ai.org", hqCity: "Zurich", hqCountry: "Switzerland", fundingAmountUsd: 50_000_000, fundingRound: "Grant", fundingDate: daysAgo(90), aiCategory: "LLM Platform", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 12, pmRoles: 1, aiRoles: 8, engRoles: 3, workMode: "Hybrid", description: "Swiss national AI initiative." }),

  seed({ name: "Legora", website: "https://legora.com", hqCity: "Stockholm", hqCountry: "Sweden", fundingAmountUsd: 25_000_000, fundingRound: "Series A", fundingDate: daysAgo(30), aiCategory: "Enterprise AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 10, pmRoles: 1, aiRoles: 3, engRoles: 6, workMode: "Hybrid", description: "AI workspace for lawyers." }),
  seed({ name: "Einride", website: "https://einride.tech", hqCity: "Stockholm", hqCountry: "Sweden", fundingAmountUsd: 500_000_000, fundingRound: "Series D+", fundingDate: daysAgo(100), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 25, pmRoles: 2, aiRoles: 8, engRoles: 15, workMode: "Hybrid", description: "Autonomous electric freight technology." }),
  seed({ name: "Peltarion", website: "https://peltarion.com", hqCity: "Stockholm", hqCountry: "Sweden", fundingAmountUsd: 35_000_000, fundingRound: "Series B", fundingDate: daysAgo(120), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 8, pmRoles: 1, aiRoles: 4, engRoles: 3, workMode: "Hybrid", description: "No-code deep learning platform." }),

  seed({ name: "Cognigy", website: "https://cognigy.com", hqCity: "Dusseldorf", hqCountry: "Germany", fundingAmountUsd: 100_000_000, fundingRound: "Series C", fundingDate: daysAgo(50), aiCategory: "Enterprise AI", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 22, pmRoles: 2, aiRoles: 7, engRoles: 13, workMode: "Hybrid", description: "Conversational AI automation platform." }),
  seed({ name: "Tractable", website: "https://tractable.ai", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 65_000_000, fundingRound: "Series D+", fundingDate: daysAgo(90), aiCategory: "Computer Vision", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 18, pmRoles: 2, aiRoles: 6, engRoles: 10, workMode: "Hybrid", description: "AI for visual damage assessment." }),

  seed({ name: "Hebbia", website: "https://hebbia.ai", hqCity: "Dublin", hqCountry: "Ireland", fundingAmountUsd: 130_000_000, fundingRound: "Series B", fundingDate: daysAgo(35), aiCategory: "Enterprise AI", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 20, pmRoles: 2, aiRoles: 8, engRoles: 10, workMode: "Hybrid", description: "AI knowledge work platform for finance." }),
  seed({ name: "Intercom", website: "https://intercom.com", hqCity: "Dublin", hqCountry: "Ireland", fundingAmountUsd: 125_000_000, fundingRound: "Series D+", fundingDate: daysAgo(60), aiCategory: "Enterprise AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 30, pmRoles: 4, aiRoles: 10, engRoles: 16, workMode: "Hybrid", description: "AI-first customer service platform." }),

  seed({ name: "Multiverse Computing", website: "https://multiversecomputing.com", hqCity: "San Sebastian", hqCountry: "Spain", fundingAmountUsd: 27_000_000, fundingRound: "Series A", fundingDate: daysAgo(45), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 12, pmRoles: 1, aiRoles: 6, engRoles: 5, workMode: "Hybrid", description: "Quantum-inspired AI compression." }),
  seed({ name: "Wallbox", website: "https://wallbox.com", hqCity: "Barcelona", hqCountry: "Spain", fundingAmountUsd: 40_000_000, fundingRound: "Series D+", fundingDate: daysAgo(110), aiCategory: "AI Product", businessModel: "B2B2C", industry: "Artificial Intelligence", openRolesTotal: 15, pmRoles: 2, aiRoles: 3, engRoles: 10, workMode: "Hybrid", description: "Smart EV charging with AI optimization." }),

  seed({ name: "Robovision", website: "https://robovision.ai", hqCity: "Ghent", hqCountry: "Belgium", fundingAmountUsd: 42_000_000, fundingRound: "Series A", fundingDate: daysAgo(55), aiCategory: "Computer Vision", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 14, pmRoles: 1, aiRoles: 6, engRoles: 7, workMode: "Hybrid", description: "Deep learning platform for computer vision." }),
  seed({ name: "Collibra", website: "https://collibra.com", hqCity: "Brussels", hqCountry: "Belgium", fundingAmountUsd: 200_000_000, fundingRound: "Series G", fundingDate: daysAgo(130), aiCategory: "Data Platform", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 28, pmRoles: 3, aiRoles: 8, engRoles: 17, workMode: "Hybrid", description: "Data intelligence with AI governance." }),

  seed({ name: "Feedzai", website: "https://feedzai.com", hqCity: "Lisbon", hqCountry: "Portugal", fundingAmountUsd: 200_000_000, fundingRound: "Series D+", fundingDate: daysAgo(75), aiCategory: "Enterprise AI", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 22, pmRoles: 2, aiRoles: 7, engRoles: 13, workMode: "Hybrid", description: "AI for financial crime prevention." }),
  seed({ name: "Unbabel", website: "https://unbabel.com", hqCity: "Lisbon", hqCountry: "Portugal", fundingAmountUsd: 60_000_000, fundingRound: "Series C", fundingDate: daysAgo(95), aiCategory: "NLP", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 16, pmRoles: 2, aiRoles: 5, engRoles: 9, workMode: "Remote", description: "AI-powered translation for customer service." }),

  seed({ name: "Relevance AI", website: "https://relevanceai.com", hqCity: "Tallinn", hqCountry: "Estonia", fundingAmountUsd: 10_000_000, fundingRound: "Series A", fundingDate: daysAgo(20), aiCategory: "Agentic AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 8, pmRoles: 1, aiRoles: 3, engRoles: 4, workMode: "Remote", description: "Build and deploy AI agent teams." }),
  seed({ name: "Veriff", website: "https://veriff.com", hqCity: "Tallinn", hqCountry: "Estonia", fundingAmountUsd: 100_000_000, fundingRound: "Series C", fundingDate: daysAgo(85), aiCategory: "Enterprise AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 20, pmRoles: 2, aiRoles: 6, engRoles: 12, workMode: "Hybrid", description: "AI-powered identity verification." }),

  seed({ name: "Rossum", website: "https://rossum.ai", hqCity: "Prague", hqCountry: "Czech Republic", fundingAmountUsd: 100_000_000, fundingRound: "Series A", fundingDate: daysAgo(65), aiCategory: "Enterprise AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 15, pmRoles: 2, aiRoles: 5, engRoles: 8, workMode: "Hybrid", description: "AI document processing for enterprises." }),
  seed({ name: "GoodData", website: "https://gooddata.com", hqCity: "Prague", hqCountry: "Czech Republic", fundingAmountUsd: 101_000_000, fundingRound: "Series C", fundingDate: daysAgo(140), aiCategory: "Data Platform", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 18, pmRoles: 2, aiRoles: 6, engRoles: 10, workMode: "Remote", description: "AI-augmented analytics platform." }),

  seed({ name: "Superlinked", website: "https://superlinked.com", hqCity: "Budapest", hqCountry: "Hungary", fundingAmountUsd: 9_500_000, fundingRound: "Seed", fundingDate: daysAgo(10), aiCategory: "Data Platform", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 6, pmRoles: 1, aiRoles: 3, engRoles: 2, workMode: "Remote", description: "Vector compute infrastructure for AI." }),
  seed({ name: "Zalando AI", website: "https://zalando.com", hqCity: "Berlin", hqCountry: "Germany", fundingAmountUsd: 50_000_000, fundingRound: "Series B", fundingDate: daysAgo(45), aiCategory: "Marketplace", businessModel: "Marketplace", industry: "Artificial Intelligence", openRolesTotal: 25, pmRoles: 4, aiRoles: 8, engRoles: 13, workMode: "Hybrid", description: "AI-powered fashion marketplace." }),

  seed({ name: "Darktrace", website: "https://darktrace.com", hqCity: "Cambridge", hqCountry: "United Kingdom", fundingAmountUsd: 100_000_000, fundingRound: "Growth", fundingDate: daysAgo(100), aiCategory: "Enterprise AI", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 20, pmRoles: 2, aiRoles: 6, engRoles: 12, workMode: "Hybrid", description: "Self-learning AI for cybersecurity." }),
  seed({ name: "Quantexa", website: "https://quantexa.com", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 175_000_000, fundingRound: "Series E", fundingDate: daysAgo(55), aiCategory: "Data Platform", businessModel: "Enterprise SaaS", industry: "Artificial Intelligence", openRolesTotal: 22, pmRoles: 2, aiRoles: 7, engRoles: 13, workMode: "Hybrid", description: "Contextual AI for decision intelligence." }),
  seed({ name: "Signal AI", website: "https://signal-ai.com", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 50_000_000, fundingRound: "Series C", fundingDate: daysAgo(70), aiCategory: "Enterprise AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 14, pmRoles: 1, aiRoles: 5, engRoles: 8, workMode: "Hybrid", description: "AI-powered media intelligence." }),
  seed({ name: "Peak AI", website: "https://peak.ai", hqCity: "Manchester", hqCountry: "United Kingdom", fundingAmountUsd: 75_000_000, fundingRound: "Series C", fundingDate: daysAgo(80), aiCategory: "Enterprise AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 16, pmRoles: 2, aiRoles: 5, engRoles: 9, workMode: "Hybrid", description: "Decision intelligence for commercial teams." }),
  seed({ name: "Fractile", website: "https://fractile.ai", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 15_000_000, fundingRound: "Seed", fundingDate: daysAgo(5), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 7, pmRoles: 1, aiRoles: 4, engRoles: 2, workMode: "Hybrid", description: "LLM inference optimization hardware-software." }),
  seed({ name: "Isomorphic Labs", website: "https://isomorphiclabs.com", hqCity: "London", hqCountry: "United Kingdom", fundingAmountUsd: 600_000_000, fundingRound: "Series A", fundingDate: daysAgo(30), aiCategory: "Healthcare AI", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 25, pmRoles: 2, aiRoles: 15, engRoles: 8, workMode: "Hybrid", description: "DeepMind spinout for AI drug discovery." }),
  seed({ name: "Magic AI", website: "https://magic.dev", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 145_000_000, fundingRound: "Series B", fundingDate: daysAgo(15), aiCategory: "Developer Tools", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 18, pmRoles: 2, aiRoles: 8, engRoles: 8, workMode: "Remote", description: "AI software engineer for code generation." }),
  seed({ name: "Kyutai", website: "https://kyutai.org", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 300_000_000, fundingRound: "Series A", fundingDate: daysAgo(25), aiCategory: "LLM Platform", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 20, pmRoles: 1, aiRoles: 12, engRoles: 7, workMode: "Hybrid", description: "Open-science AI research lab." }),
  seed({ name: "LightOn", website: "https://lighton.ai", hqCity: "Paris", hqCountry: "France", fundingAmountUsd: 30_000_000, fundingRound: "Series A", fundingDate: daysAgo(50), aiCategory: "AI Infrastructure", businessModel: "B2B SaaS", industry: "Artificial Intelligence", openRolesTotal: 10, pmRoles: 1, aiRoles: 5, engRoles: 4, workMode: "Hybrid", description: "Optical processing for AI compute." }),
];
